version: "3.9"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:9.3.6
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  grafana-broker:
    container_name: grafana-broker
    image: eclipse-mosquitto:2.0.15
    restart: unless-stopped
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  converter:
    container_name: grafana-converter
    image: converter
    build: ./converter
    restart: unless-stopped
    environment:
      GRAFANA_BROKER: grafana-broker
      GRAFANA_BROKER_PORT: 1883
      CCOM_BROKER: ccom-broker
      CCOM_BROKER_PORT: ${CCOM_BROKER_PORT}
      CCOM_BROKER_USERNAME: ${CCOM_BROKER_USERNAME}
      CCOM_BROKER_PASSWORD: ${CCOM_BROKER_PASSWORD}
    extra_hosts:
      - "ccom-broker:${CCOM_BROKER_IP}"
    depends_on:
      - grafana-broker

volumes:
  grafana-storage:
